# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-toml
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.18.0
    hooks:
    -   id: pyupgrade
        args:
        - --py3-plus
        - --keep-runtime-typing
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.6.9
    hooks:
    -   id: ruff
        args:
        - --fix
-   repo: https://github.com/PyCQA/bandit
    rev: '1.7.4'
    hooks:
    -   id: bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]
-   repo: https://github.com/PyCQA/autoflake
    rev: v2.0.0
    hooks:
    -   id: autoflake

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.13.0'
    hooks:
    -   id: mypy

ci:
    autofix_commit_msg: fix(pre-commit):🎨 Auto format from pre-commit.com hooks
    autoupdate_commit_msg: dev(pre-commit):⬆ pre-commit autoupdate
