# Generated by Django 4.1.1 on 2022-09-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TestModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("integer_field", models.IntegerField(null=True)),
                ("char_field", models.CharField(max_length=32, null=True)),
                ("boolean_field", models.BooleanField(default=False)),
                ("datetime_field", models.DateTimeField(null=True)),
                ("json_field", models.JSONField(null=True)),
            ],
        ),
    ]
